-- MySQL Script generated by MySQL Workbench
-- Wed Jun 23 07:55:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PRUEBA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PRUEBA` ;

-- -----------------------------------------------------
-- Schema PRUEBA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PRUEBA` ;
USE `PRUEBA` ;

-- -----------------------------------------------------
-- Table `PRUEBA`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`DEPARTAMENTO` (
  `NumDepto` INT NOT NULL,
  `NomDepto` VARCHAR(45) NOT NULL,
  `FechaGte` VARCHAR(45) NOT NULL,
  `EMPLEADO_NSS` INT NOT NULL,
  PRIMARY KEY (`NumDepto`),
  CONSTRAINT `fk_DEPARTAMENTO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_NSS`)
    REFERENCES `PRUEBA`.`EMPLEADO` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DEPARTAMENTO_EMPLEADO1_idx` ON `PRUEBA`.`DEPARTAMENTO` (`EMPLEADO_NSS` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`EMPLEADO` (
  `NSS` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `FechaNac` DATETIME NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `EMPLEADO_NSS` INT NOT NULL,
  `DEPARTAMENTO_NumDepto` INT NOT NULL,
  PRIMARY KEY (`NSS`),
  CONSTRAINT `fk_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_NSS`)
    REFERENCES `PRUEBA`.`EMPLEADO` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_NumDepto`)
    REFERENCES `PRUEBA`.`DEPARTAMENTO` (`NumDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLEADO_EMPLEADO1_idx` ON `PRUEBA`.`EMPLEADO` (`EMPLEADO_NSS` ASC) VISIBLE;

CREATE INDEX `fk_EMPLEADO_DEPARTAMENTO1_idx` ON `PRUEBA`.`EMPLEADO` (`DEPARTAMENTO_NumDepto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`DEPENDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`DEPENDIENTE` (
  `NOMBRE` INT NOT NULL,
  `Parentesco` VARCHAR(45) NOT NULL,
  `Empleado_NSS` INT NOT NULL,
  `Edad` INT NOT NULL,
  `Fechanac` DATETIME NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NOMBRE`),
  CONSTRAINT `fk_DEPENDIENTE_EMPLEADO`
    FOREIGN KEY (`Empleado_NSS`)
    REFERENCES `PRUEBA`.`EMPLEADO` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DEPENDIENTE_EMPLEADO_idx` ON `PRUEBA`.`DEPENDIENTE` (`Empleado_NSS` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`PROYECTO` (
  `NUMPROY` INT NOT NULL,
  `NomProy` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `DEPARTAMENTO_NumDepto` INT NOT NULL,
  PRIMARY KEY (`NUMPROY`),
  CONSTRAINT `fk_PROYECTO_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_NumDepto`)
    REFERENCES `PRUEBA`.`DEPARTAMENTO` (`NumDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROYECTO_DEPARTAMENTO1_idx` ON `PRUEBA`.`PROYECTO` (`DEPARTAMENTO_NumDepto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`TRABAJAEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`TRABAJAEN` (
  `EMPLEADO_NSS` INT NOT NULL,
  `PROYECTO_NUMPROY` INT NOT NULL,
  `Horas` INT NOT NULL,
  PRIMARY KEY (`EMPLEADO_NSS`, `PROYECTO_NUMPROY`),
  CONSTRAINT `fk_EMPLEADO_has_PROYECTO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_NSS`)
    REFERENCES `PRUEBA`.`EMPLEADO` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_has_PROYECTO_PROYECTO1`
    FOREIGN KEY (`PROYECTO_NUMPROY`)
    REFERENCES `PRUEBA`.`PROYECTO` (`NUMPROY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLEADO_has_PROYECTO_PROYECTO1_idx` ON `PRUEBA`.`TRABAJAEN` (`PROYECTO_NUMPROY` ASC) VISIBLE;

CREATE INDEX `fk_EMPLEADO_has_PROYECTO_EMPLEADO1_idx` ON `PRUEBA`.`TRABAJAEN` (`EMPLEADO_NSS` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`LOCALIDAD` (
  `LOCALIDAD` INT NOT NULL,
  `DEPARTAMENTO_NumDepto` INT NOT NULL,
  PRIMARY KEY (`LOCALIDAD`, `DEPARTAMENTO_NumDepto`),
  CONSTRAINT `fk_LOCALIDAD_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_NumDepto`)
    REFERENCES `PRUEBA`.`DEPARTAMENTO` (`NumDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_LOCALIDAD_DEPARTAMENTO1_idx` ON `PRUEBA`.`LOCALIDAD` (`DEPARTAMENTO_NumDepto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Proyecto` (
  `idProy` VARCHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Cliente` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idProy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Empleado` (
  `idEmpleado` VARCHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Experiencia` INT NOT NULL,
  `Telefono` VARCHAR(10) CHARACTER SET 'armscii8' NOT NULL,
  `Informatico` VARCHAR(45) NOT NULL,
  `Jefe de Proyecto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Gasto` (
  `idGasto` VARCHAR(3) NOT NULL,
  `Empleado_idEmpleado` VARCHAR(3) NOT NULL,
  `Proyecto_idProy` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idGasto`),
  CONSTRAINT `fk_Gasto_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `PRUEBA`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gasto_Proyecto1`
    FOREIGN KEY (`Proyecto_idProy`)
    REFERENCES `PRUEBA`.`Proyecto` (`idProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gasto_Empleado1_idx` ON `PRUEBA`.`Gasto` (`Empleado_idEmpleado` ASC) VISIBLE;

CREATE INDEX `fk_Gasto_Proyecto1_idx` ON `PRUEBA`.`Gasto` (`Proyecto_idProy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Fase` (
  `idFase` VARCHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Proyecto_idProy` VARCHAR(3) NOT NULL,
  `Fin` DATE NOT NULL,
  PRIMARY KEY (`idFase`, `Proyecto_idProy`),
  CONSTRAINT `fk_Fase_Proyecto1`
    FOREIGN KEY (`Proyecto_idProy`)
    REFERENCES `PRUEBA`.`Proyecto` (`idProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fase_Proyecto1_idx` ON `PRUEBA`.`Fase` (`Proyecto_idProy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Recurso` (
  `idRecurso` VARCHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Producto` (
  `idProducto` VARCHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRUEBA`.`SW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`SW` (
  `Tipo` VARCHAR(45) NOT NULL,
  `Producto_idProducto` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  CONSTRAINT `fk_SW_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `PRUEBA`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SW_Producto1_idx` ON `PRUEBA`.`SW` (`Producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Prototipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Prototipo` (
  `Estado` VARCHAR(45) NOT NULL,
  `SW_Producto_idProducto` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`SW_Producto_idProducto`),
  CONSTRAINT `fk_Prototipo_SW1`
    FOREIGN KEY (`SW_Producto_idProducto`)
    REFERENCES `PRUEBA`.`SW` (`Producto_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prototipo_SW1_idx` ON `PRUEBA`.`Prototipo` (`SW_Producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Genera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Genera` (
  `Fase_idFase` VARCHAR(3) NOT NULL,
  `Producto_idProducto` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Fase_idFase`, `Producto_idProducto`),
  CONSTRAINT `fk_Fase_has_Producto_Fase1`
    FOREIGN KEY (`Fase_idFase`)
    REFERENCES `PRUEBA`.`Fase` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fase_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `PRUEBA`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fase_has_Producto_Producto1_idx` ON `PRUEBA`.`Genera` (`Producto_idProducto` ASC) VISIBLE;

CREATE INDEX `fk_Fase_has_Producto_Fase1_idx` ON `PRUEBA`.`Genera` (`Fase_idFase` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Informatico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Informatico` (
  `idEmpleado` VARCHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Experiencia` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Analista` VARCHAR(45) NOT NULL,
  `Programador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Correo` (
  `Correo` VARCHAR(45) NOT NULL,
  `Empleado_idEmpleado` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Correo`),
  CONSTRAINT `fk_Correo_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `PRUEBA`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Correo_Empleado1_idx` ON `PRUEBA`.`Correo` (`Empleado_idEmpleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Labora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Labora` (
  `Proyecto_idProy` VARCHAR(3) NOT NULL,
  `Empleado_idEmpleado` VARCHAR(3) NOT NULL,
  `NumHoras` INT NOT NULL,
  `CostoT` INT NOT NULL,
  PRIMARY KEY (`Proyecto_idProy`, `Empleado_idEmpleado`),
  CONSTRAINT `fk_Proyecto_has_Empleado_Proyecto1`
    FOREIGN KEY (`Proyecto_idProy`)
    REFERENCES `PRUEBA`.`Proyecto` (`idProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `PRUEBA`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Proyecto_has_Empleado_Empleado1_idx` ON `PRUEBA`.`Labora` (`Empleado_idEmpleado` ASC) VISIBLE;

CREATE INDEX `fk_Proyecto_has_Empleado_Proyecto1_idx` ON `PRUEBA`.`Labora` (`Proyecto_idProy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Pertenece` (
  `Recurso_idRecurso` VARCHAR(3) NOT NULL,
  `Fase_idFase` VARCHAR(3) NOT NULL,
  `Inicio` DATE NOT NULL,
  `Fin` DATE NOT NULL,
  PRIMARY KEY (`Recurso_idRecurso`, `Fase_idFase`),
  CONSTRAINT `fk_Recurso_has_Fase_Recurso1`
    FOREIGN KEY (`Recurso_idRecurso`)
    REFERENCES `PRUEBA`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recurso_has_Fase_Fase1`
    FOREIGN KEY (`Fase_idFase`)
    REFERENCES `PRUEBA`.`Fase` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Recurso_has_Fase_Fase1_idx` ON `PRUEBA`.`Pertenece` (`Fase_idFase` ASC) VISIBLE;

CREATE INDEX `fk_Recurso_has_Fase_Recurso1_idx` ON `PRUEBA`.`Pertenece` (`Recurso_idRecurso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Se involucra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Se involucra` (
  `Fase_idFase` VARCHAR(3) NOT NULL,
  `Producto_idProducto` VARCHAR(5) NOT NULL,
  `Informatico_idEmpleado` VARCHAR(3) NOT NULL,
  `NumHoras` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fase_idFase`, `Producto_idProducto`, `Informatico_idEmpleado`, `NumHoras`),
  CONSTRAINT `fk_Fase_has_Producto_Fase2`
    FOREIGN KEY (`Fase_idFase`)
    REFERENCES `PRUEBA`.`Fase` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fase_has_Producto_Producto2`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `PRUEBA`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Se involucra_Informatico1`
    FOREIGN KEY (`Informatico_idEmpleado`)
    REFERENCES `PRUEBA`.`Informatico` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fase_has_Producto_Producto2_idx` ON `PRUEBA`.`Se involucra` (`Producto_idProducto` ASC) VISIBLE;

CREATE INDEX `fk_Fase_has_Producto_Fase2_idx` ON `PRUEBA`.`Se involucra` (`Fase_idFase` ASC) VISIBLE;

CREATE INDEX `fk_Se involucra_Informatico1_idx` ON `PRUEBA`.`Se involucra` (`Informatico_idEmpleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Lenguaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Lenguaje` (
  `Informatico_idEmpleado` VARCHAR(3) NOT NULL,
  `Lenguaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Informatico_idEmpleado`, `Lenguaje`),
  CONSTRAINT `fk_Informatico_has_Informatico_Informatico1`
    FOREIGN KEY (`Informatico_idEmpleado`)
    REFERENCES `PRUEBA`.`Informatico` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Informatico_has_Informatico_Informatico1_idx` ON `PRUEBA`.`Lenguaje` (`Informatico_idEmpleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PRUEBA`.`Relacionado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRUEBA`.`Relacionado` (
  `Proyecto_idProy` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Proyecto_idProy`),
  CONSTRAINT `fk_Proyecto_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_idProy`)
    REFERENCES `PRUEBA`.`Proyecto` (`idProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Proyecto_has_Proyecto_Proyecto1_idx` ON `PRUEBA`.`Relacionado` (`Proyecto_idProy` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
